// GENERATED CODE - DO NOT EDIT BY HAND.
// Generated by tool/gen_crisp_font.py from ABA Games crisp-game-lib src/textPattern.ts.
// Upstream source is MIT; see THIRD_PARTY_NOTICES.md.

const crispTextFirstCodePoint = 0x21;
const crispTextLastCodePoint = 0x7e;

const crispTextPatterns = <String>[
  // U+0021  !
  r'''
l
l
l

l
''',
  // U+0022  "
  r'''
l l
l l



''',
  // U+0023  #
  r'''
 l l
lllll
 l l
lllll
 l l
''',
  // U+0024  $
  r'''
 lll
l l
 lll
  l l
 lll
''',
  // U+0025  %
  r'''
l   l
l  l
  l
 l  l
l   l
''',
  // U+0026  &
  r'''
 l
l l
 ll l
l  l
 ll l
''',
  // U+0027  '
  r'''
l
l



''',
  // U+0028  (
  r'''
 l
l
l
l
 l
''',
  // U+0029  )
  r'''
l
 l
 l
 l
l
''',
  // U+002A  *
  r'''
  l
l l l
 lll
l l l
  l
''',
  // U+002B  +
  r'''
  l
  l
lllll
  l
  l
''',
  // U+002C  ,
  r'''



 l
l
''',
  // U+002D  -
  r'''


lllll


''',
  // U+002E  .
  r'''




l
''',
  // U+002F  /
  r'''
    l
   l
  l
 l
l
''',
  // U+0030  0
  r'''
 lll
l  ll
l l l
ll  l
 lll
''',
  // U+0031  1
  r'''
 ll
l l
  l
  l
lllll
''',
  // U+0032  2
  r'''
 lll
l   l
  ll
 l
lllll
''',
  // U+0033  3
  r'''
llll
    l
  ll
    l
llll
''',
  // U+0034  4
  r'''
  ll
 l l
l  l
lllll
   l
''',
  // U+0035  5
  r'''
lllll
l
llll
    l
llll
''',
  // U+0036  6
  r'''
 lll
l
llll
l   l
 lll
''',
  // U+0037  7
  r'''
lllll
l   l
   l
  l
 l
''',
  // U+0038  8
  r'''
 lll
l   l
 lll
l   l
 lll
''',
  // U+0039  9
  r'''
 lll
l   l
 llll
    l
 lll
''',
  // U+003A  :
  r'''

l

l

''',
  // U+003B  ;
  r'''

 l

 l
l
''',
  // U+003C  <
  r'''
   ll
 ll
l
 ll
   ll
''',
  // U+003D  =
  r'''

lllll

lllll

''',
  // U+003E  >
  r'''
ll
  ll
    l
  ll
ll
''',
  // U+003F  ?
  r'''
 lll
l   l
  ll

  l
''',
  // U+0040  @
  r'''
 lll
l   l
l lll
l
 lll
''',
  // U+0041  A
  r'''
 lll
l   l
lllll
l   l
l   l
''',
  // U+0042  B
  r'''
llll
l   l
llll
l   l
llll
''',
  // U+0043  C
  r'''
 llll
l
l
l
 llll
''',
  // U+0044  D
  r'''
llll
l   l
l   l
l   l
llll
''',
  // U+0045  E
  r'''
lllll
l
llll
l
lllll
''',
  // U+0046  F
  r'''
lllll
l
llll
l
l
''',
  // U+0047  G
  r'''
 lll
l
l  ll
l   l
 llll
''',
  // U+0048  H
  r'''
l   l
l   l
lllll
l   l
l   l
''',
  // U+0049  I
  r'''
lllll
  l
  l
  l
lllll
''',
  // U+004A  J
  r'''
  lll
   l
   l
   l
lll
''',
  // U+004B  K
  r'''
l   l
l  l
lll
l  l
l   l
''',
  // U+004C  L
  r'''
l
l
l
l
lllll
''',
  // U+004D  M
  r'''
l   l
ll ll
l l l
l   l
l   l
''',
  // U+004E  N
  r'''
l   l
ll  l
l l l
l  ll
l   l
''',
  // U+004F  O
  r'''
 lll
l   l
l   l
l   l
 lll
''',
  // U+0050  P
  r'''
llll
l   l
llll
l
l
''',
  // U+0051  Q
  r'''
 lll
l   l
l   l
l  ll
 llll
''',
  // U+0052  R
  r'''
llll
l   l
llll
l   l
l   l
''',
  // U+0053  S
  r'''
 llll
l
 lll
    l
llll
''',
  // U+0054  T
  r'''
lllll
  l
  l
  l
  l
''',
  // U+0055  U
  r'''
l   l
l   l
l   l
l   l
 lll
''',
  // U+0056  V
  r'''
l   l
l   l
l   l
 l l
  l
''',
  // U+0057  W
  r'''
l   l
l l l
l l l
l l l
 l l
''',
  // U+0058  X
  r'''
l   l
 l l
  l
 l l
l   l
''',
  // U+0059  Y
  r'''
l   l
 l l
  l
  l
  l
''',
  // U+005A  Z
  r'''
lllll
   l
  l
 l
lllll
''',
  // U+005B  [
  r'''
  ll
  l
  l
  l
  ll
''',
  // U+005C  \\
  r'''
l
 l
  l
   l
    l
''',
  // U+005D  ]
  r'''
 ll
  l
  l
  l
 ll
''',
  // U+005E  ^
  r'''
  l
 l l



''',
  // U+005F  _
  r'''




lllll
''',
  // U+0060  `
  r'''
 l
  l



''',
  // U+0061  a
  r'''

 lll
l  l
l  l
 lll
''',
  // U+0062  b
  r'''
l
l
lll
l  l
lll
''',
  // U+0063  c
  r'''

 lll
l  
l
 lll
''',
  // U+0064  d
  r'''
   l
   l
 lll
l  l
 lll
''',
  // U+0065  e
  r'''

 ll
l ll
ll
 ll
''',
  // U+0066  f
  r'''
  l
 l 
lll
 l
 l
''',
  // U+0067  g
  r'''
 ll
l  l
 lll
   l
 ll
''',
  // U+0068  h
  r'''
l
l
ll
l l
l l
''',
  // U+0069  i
  r'''

l

l
l
''',
  // U+006A  j
  r'''
 l

 l
 l
l
''',
  // U+006B  k
  r'''
l
l
l l
ll
l l
''',
  // U+006C  l
  r'''
ll
 l
 l
 l
lll
''',
  // U+006D  m
  r'''

llll
l l l
l l l
l   l
''',
  // U+006E  n
  r'''

lll
l  l
l  l
l  l
''',
  // U+006F  o
  r'''

 ll
l  l
l  l
 ll
''',
  // U+0070  p
  r'''

lll
l  l
lll
l
''',
  // U+0071  q
  r'''

 lll
l  l
 lll
   l
''',
  // U+0072  r
  r'''

l ll
ll
l
l
''',
  // U+0073  s
  r'''

 lll
ll
  ll
lll
''',
  // U+0074  t
  r'''

 l
lll
 l
  l
''',
  // U+0075  u
  r'''

l  l
l  l
l  l
 lll
''',
  // U+0076  v
  r'''

l  l
l  l
 ll
 ll
''',
  // U+0077  w
  r'''

l   l
l l l
l l l
 l l
''',
  // U+0078  x
  r'''

l  l
 ll
 ll
l  l
''',
  // U+0079  y
  r'''

l  l
 ll
 l
l
''',
  // U+007A  z
  r'''

llll
  l
 l
llll
''',
  // U+007B  {
  r'''
 ll
 l
l
 l
 ll
''',
  // U+007C  |
  r'''
l
l
l
l
l
''',
  // U+007D  }
  r'''
ll
 l
  l
 l
ll
''',
  // U+007E  ~
  r'''

 l
l l l
   l

''',
];
