#!/usr/bin/env python3
from pathlib import Path
import re
import sys

if len(sys.argv) != 2:
    raise SystemExit(
        "usage: python3 tool/gen_crisp_font.py /path/to/crisp-game-lib/src/textPattern.ts"
    )

source_path = Path(sys.argv[1])
source = source_path.read_text()
body = source.split("export const textPatterns = [", 1)[1].rsplit("];", 1)[0]
patterns = re.findall(r"`(.*?)`", body, re.S)

first_code_point = 0x21
last_code_point = first_code_point + len(patterns) - 1

out = [
    "// GENERATED CODE - DO NOT EDIT BY HAND.",
    "// Generated by tool/gen_crisp_font.py from ABA Games crisp-game-lib src/textPattern.ts.",
    "// Upstream source is MIT; see THIRD_PARTY_NOTICES.md.",
    "",
    f"const crispTextFirstCodePoint = 0x{first_code_point:02x};",
    f"const crispTextLastCodePoint = 0x{last_code_point:02x};",
    "",
    "const crispTextPatterns = <String>[",
]

for index, pattern in enumerate(patterns):
    code_point = first_code_point + index
    character = chr(code_point)
    display = "\\" if character == "\\" else character
    pattern = pattern.replace("\\", "\\\\").replace("'''", "\\'\\'\\'")
    out.append(f"  // U+{code_point:04X}  {display}")
    out.append("  r'''" + pattern + "''',")

out.append("];")

target = Path("lib/src/font_data.dart")
target.write_text("\n".join(out) + "\n")
print(f"wrote {len(patterns)} patterns to {target}")
